### ISSUE TITLE
Error when use it in my github actions yaml.

### ISSUE THREAD

**Issue by koteswara-kelam** [einaregilsson/build-number#8]
Run einaregilsson/build-number@v2
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo EAI_AGAIN api.github.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'api.github.com'
}
##[error]Node run failed with exit code 1

**Comment by einaregilsson** [comment]
That looks like it failed to lookup the address for api.github.com. That's not really something we can handle in the action. Does this happen consistently for you?

**Comment by koteswara-kelam** [comment]
I tried only once.

**Comment by einaregilsson** [comment]
Ok, I would guess that it's a one-off error and would work the next time.

**Comment by einaregilsson** [comment]
Closing this, sounds like a network error and haven't heard back.
